<?php

//define constants
define("KALTURA_PARTNER_ID", ENTER YOUR PARTNER ID HERE);
define("KALTURA_PARTNER_USER", "example.com or make something up");
define("KALTURA_PARTNER_WEB_SERVICE_SECRET", "ENTER YOUR PARTNER SECRET HERE");
define("KALTURA_PARTNER_WEB_SERVICE_ADMIN_SECRET", "ENTER YOUR PARTNER ADMIN SECRET HERE");

?>
